const keywords = [
  'action',
  'adventure',
  'alien',
  'apocalypse',
  'assassin',
  'battle',
  'biography',
  'comedy',
  'crime',
  'cyberpunk',
  'detective',
  'disaster',
  'drama',
  'espionage',
  'fantasy',
  'future',
  'gangster',
  'ghost',
  'hero',
  'horror',
  'invasion',
  'journey',
  'love',
  'martial arts',
  'mystery',
  'post-apocalyptic',
  'robot',
  'romance',
  'sci-fi',
  'space',
  'spy',
  'survival',
  'suspense',
  'technology',
  'thriller',
  'time travel',
  'vampire',
  'virus',
  'war',
  'witch',
  'zombie',
  'supernatural',
  'villain',
  'revolution',
  'dystopia',
  'military',
  'pandemic',
  'underground',
  'magic',
];

export function getRandomKeyword(): string {
  const index = Math.floor(Math.random() * keywords.length);
  return keywords[index];
}
